# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# --- Dockerfile for dify-mcp-server ---

# Builder stage
FROM node:lts-alpine AS builder
WORKDIR /app

# Copy manifest and TS config
COPY package.json package-lock.json tsconfig.json ./
# Copy source
COPY src ./src

# Install all deps (skip scripts to avoid premature build), then build
RUN npm ci --ignore-scripts
RUN npm run build

# Runtime stage
FROM node:lts-alpine AS runtime
WORKDIR /app

# Copy only prod dependencies manifest
COPY package.json package-lock.json ./
# Install prod deps without running scripts
RUN npm ci --omit=dev --ignore-scripts

# Copy built output from builder
COPY --from=builder /app/build ./build

# Ensure executable permission on entry
RUN chmod +x build/index.js

# Default command to start MCP server
CMD ["node", "build/index.js"]

# Expose nothing; uses stdio transport by default
